version: "3.9"

services:
  # Postgres database
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=my_database
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - my_network
    ports:
      - "5432:5432"

  # Python shell with requirements.txt
  jupyter:
      build:
          context: .
          dockerfile: notebook/Dockerfile
      ports:
          - 8888:8888
      volumes:
          - ./notebook:/notebook
          - ./data:/data
      environment:
          - JUPYTER_ENABLE_LAB=yes
          - NB_USER=infomdss
          - CHOWN_HOME=yes
      working_dir: /notebook

  # Streamlit service
  streamlit:
    build:
      dockerfile: ./streamlit/Dockerfile
    command: streamlit run app.py
    volumes:
      - ./streamlit:/streamlit
    networks:
      - my_network
    ports:
      - "8501:8501"

networks:
  my_network: