version: "3.9"

services:
  # Postgres database
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=my_database
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - my_network
    ports:
      - "5432:5432"

  # Uploader service
  uploader:
    build:
      dockerfile: ./data/Dockerfile
    command: python3 uploader.py
    volumes:
      - csv_volume:/app/data
    networks:
      - my_network

  # Streamlit service
  streamlit:
    build:
      dockerfile: ./dashboard/Dockerfile
    volumes:
      - ./dashboard:/dashboard
    networks:
      - my_network
    ports:
      - "8501:8501"

volumes:
  csv_volume: {}

networks:
  my_network: