version: "3.9"

services:
  # Postgres database
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=my_database
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - my_network
    ports:
      - "5432:5432"

  # Python shell with requirements.txt
  notebook:
    build: 
      dockerfile: ./notebook/Dockerfile
    volumes:
      - ./notbook:/app
    environment:
    - NAME=Flask-App
    - PYTHONPATH=/app
    working_dir: /app
    networks:
      - my_network

  # Streamlit service
  streamlit:
    build:
      dockerfile: ./streamlit/Dockerfile
    command: streamlit run app.py
    volumes:
      - ./streamlit:/streamlit
    networks:
      - my_network
    ports:
      - "8501:8501"

networks:
  my_network: